[server]
headless = true
port = 8501  # Default port, change if needed
enableCORS = false  # Disable CORS to allow access from other domains
enableXsrfProtection = false  # Disable XSRF protection if needed for development

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"

[browser]
gatherUsageStats = false  # Opt-out of usage statistics

[logging]
level = "info"  # Set logging level (e.g., "debug", "info", "warning", "error")